name: Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MSBuild tools
      run: |
        choco install microsoft-build-tools --version=16.11.2 --no-progress --yes

    - name: Restore dependencies
      run: nuget restore Curs/Curs.sln # Используйте команду nuget для восстановления зависимостей

    - name: Build project
      run: msbuild Curs/Curs.sln /p:Configuration=Release /p:Platform="Any CPU" # Сборка с помощью MSBuild

    - name: Check code formatting (optional)
      run: echo "No automatic format check available for .NET Framework."
